// Generated by gmmproc 2.74.0 -- DO NOT MODIFY!
#ifndef _GIOMM_FILEDESCRIPTORBASED_H
#define _GIOMM_FILEDESCRIPTORBASED_H

#include <giommconfig.h>


#include <glibmm/ustring.h>
#include <sigc++/sigc++.h>

/* Copyright (C) 2017 The giomm Development Team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */


#include <glibmm/interface.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GFileDescriptorBasedIface GFileDescriptorBasedIface;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

#ifndef DOXYGEN_SHOULD_SKIP_THIS
using GFileDescriptorBased = struct _GFileDescriptorBased;
using GFileDescriptorBasedClass = struct _GFileDescriptorBasedClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


#ifndef DOXYGEN_SHOULD_SKIP_THIS
namespace Gio
{ class GIOMM_API FileDescriptorBased_Class; } // namespace Gio
#endif // DOXYGEN_SHOULD_SKIP_THIS

namespace Gio
{

/** Interface for file descriptor based IO.
 *
 * %FileDescriptorBased is implemented by streams (implementations of
 * Gio::InputStream or Gio::OutputStream) that are based on file descriptors.
 *
 * @ingroup Streams
 *
 * @newin{2,58}
 */

class FileDescriptorBased : public Glib::Interface
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  using CppObjectType = FileDescriptorBased;
  using CppClassType = FileDescriptorBased_Class;
  using BaseObjectType = GFileDescriptorBased;
  using BaseClassType = GFileDescriptorBasedIface;

  // noncopyable
  FileDescriptorBased(const FileDescriptorBased&) = delete;
  FileDescriptorBased& operator=(const FileDescriptorBased&) = delete;

private:
  friend class FileDescriptorBased_Class;
  static CppClassType filedescriptorbased_class_;

#endif /* DOXYGEN_SHOULD_SKIP_THIS */
protected:
  /**
   * You should derive from this class to use it.
   */
  FileDescriptorBased();

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  /** Called by constructors of derived classes. Provide the result of
   * the Class init() function to ensure that it is properly
   * initialized.
   *
   * @param interface_class The Class object for the derived type.
   */
  explicit FileDescriptorBased(const Glib::Interface_Class& interface_class);

public:
  // This is public so that C++ wrapper instances can be
  // created for C instances of unwrapped types.
  // For instance, if an unexpected C type implements the C interface.
  explicit FileDescriptorBased(GFileDescriptorBased* castitem);

protected:
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:

  FileDescriptorBased(FileDescriptorBased&& src) noexcept;
  FileDescriptorBased& operator=(FileDescriptorBased&& src) noexcept;

  ~FileDescriptorBased() noexcept override;

  static void add_interface(GType gtype_implementer);

  /** Get the GType for this class, for use with the underlying GObject type system.
   */
  static GType get_type()      G_GNUC_CONST;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GFileDescriptorBased*       gobj()       { return reinterpret_cast<GFileDescriptorBased*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GFileDescriptorBased* gobj() const { return reinterpret_cast<GFileDescriptorBased*>(gobject_); }

private:

  //This is not available on Win32.
//This source file will not be compiled on Win32,
//and no class defined in it will be registered by wrap_init().


public:
  
  /** Gets the underlying file descriptor.
   * 
   * @newin{2,58}
   * 
   * @return The file descriptor.
   */
  int get_fd() const;

protected:
    virtual int get_fd_vfunc() const;


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} // namespace Gio


namespace Glib
{
  /** A Glib::wrap() method for this object.
   *
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gio::FileDescriptorBased
   */
  GIOMM_API
  Glib::RefPtr<Gio::FileDescriptorBased> wrap(GFileDescriptorBased* object, bool take_copy = false);

} // namespace Glib


#endif /* _GIOMM_FILEDESCRIPTORBASED_H */

